version: '3.8'

services:
  bot:
    build: .
    container_name: tatar_youth_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tatar_youth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tatar_youth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: